name: Android CI

on:
  pull_request:
    branches:
      - '**'  # Esto se activará en cualquier rama que cree un pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configura Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Puedes cambiar esto por 'adopt' o 'zulu'
        java-version: '11'
        
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Cache Gradle files
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    # Configura Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: '33.0.0'
        cmake-version: '3.10.2'

    # Descarga dependencias
    - name: Download dependencies
      run: ./gradlew build --no-daemon
    
    # Ejecuta las pruebas unitarias
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --no-daemon
    
    # Ejecuta las pruebas de instrumentación (pruebas en emulador)
    - name: Run Instrumentation Tests
      run: ./gradlew connectedDebugAndroidTest --no-daemon

    # Lint y formateo de código
    - name: Run Lint
      run: ./gradlew lint --no-daemon
